[build]
command = 'hugo'
command = 'CI= npm run build'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.125.4'
HUGO_ENABLEGITINFO = "true"

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
